### ISSUE TITLE
Can't npm start on example. Fails in webpack build.

### ISSUE THREAD

**Issue by yourfavorite** [mariotacke/redux-electron-ipc#1]
Not sure if I'm the problem here but ran npm install with no errors. npm start fails in webpack build.

```
Hash: 90c6c84d52945b6618e3
Version: webpack 1.13.2
Time: 976ms
     Asset       Size  Chunks             Chunk Names
 bundle.js    1.66 kB       0  [emitted]  main
index.html  208 bytes          [emitted]  
   [0] multi main 40 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./app/app.js
Module build failed: ReferenceError: Unknown plugin "babel-plugin-add-module-exports" specified in "/Users/cbritt/Downloads/redux-electron-ipc-master/.babelrc" at 0, attempted to resolve relative to "/Users/cbritt/Downloads/redux-electron-ipc-master"
    at /Users/cbritt/Downloads/redux-electron-ipc-master/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/cbritt/Downloads/redux-electron-ipc-master/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/cbritt/Downloads/redux-electron-ipc-master/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/cbritt/Downloads/redux-electron-ipc-master/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:359:12)
    at File.initOptions (/Users/cbritt/Downloads/redux-electron-ipc-master/example/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/Users/cbritt/Downloads/redux-electron-ipc-master/example/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/Users/cbritt/Downloads/redux-electron-ipc-master/example/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/cbritt/Downloads/redux-electron-ipc-master/example/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/cbritt/Downloads/redux-electron-ipc-master/example/node_modules/babel-loader/index.js:131:12)
 @ multi main
```

**Comment by mariotacke** [comment]
Let me have a look. Looks like a missing dependency.

**Comment by mariotacke** [comment]
Give it a go now. I did not update the example after I introduced a feature in 1.1.0. My apologies.
